/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scot.launchquickly;

import java.util.Optional;

public class App {
    public static void main(String[] args) {
        final String name;
        if (args.length == 0) {
            name = null;
        } else {
            name = args[0];
        }
        System.out.println(new App().hello(name));
    }

    String hello(final String name) {
        return String.format("Hello, %s!", Optional.ofNullable(name).orElseGet(() ->"world"));
    }
}
